version: "3"
services:
    php-apache:
        image: php:7.3.3-apache
        ports:
            - 80:80
        volumes:
            - ./http:/var/www/html
            - ./conf/apache2/apache2.conf:/etc/apache2/apache2.conf
            - ./conf/apache2/sites-enabled:/etc/apache2/sites-enabled
            - ./conf/php7.3/php.ini:/etc/php/7.3/apache2/php.ini
        links:
            - 'mariadb'
    # www:
    #     build: .
    #     ports: 
    #         - "8000:80"
    #     volumes:
    #         - ./www:/var/www/html/
    #     links:
    #         - db
    #     networks:
    #         - default
    mariadb:
        image: mariadb:10.1
        # image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./conf/mariadb10/db:/var/lib/mysql
            - ./conf/mariadb10/dump:/docker-entrypoint-initdb.d
        environment:
            TZ: "America/Sao_Paulo"
            # MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
            MYSQL_DATABASE: 'data'
        networks:
            - default