version: '3'
services:
  # mariadb 10
  data:
    build: ./mariadb
    environment:
      - MYSQL_DATABASE='test'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='root'
      - MYSQL_ROOT_PASSWORD='root'
    volumes:
      - ./mariadb/db:/var/lib/mysql
      - ./mariadb/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
  
  # php-fpm 7.3
  php:
    build: ./php
    ports:
      - "9000:9000"

  # nginx alpine
  nginx:
    build: ./nginx
    volumes:
      - ./http:/srv/http
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"